### ISSUE TITLE
Support Creation of prefilled Peak Award form

### ISSUE THREAD

**Issue by samuel-2004** [NomisNostab/Topo-Blazor#142]
I am not aware how it works in other states. In WA you are required to fill a peak award form. It would be handy if the site had an option to create and download a filled version of one of these forms once the youth member had completed their peak award.

**Comment by NomisNostab** [comment]
Hi Samuel,
I have thought about doing that, but the difficulties of filling in form fields and the potential backlash from Scouts Aus for using one of their forms made me think otherwise.
Instead I created the Personal Progress report which has much of the information needed to fill out the Peak Award form.
Simon

**Comment by NomisNostab** [comment]
Hi Samuel,

Ok to close this issue?
Simon.
